# Generated by Django 5.0.7 on 2024-08-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('réalisateur', models.CharField(max_length=255)),
                ('image_couverture', models.ImageField(upload_to='couvertures/')),
                ('vidéo_complète', models.FileField(upload_to='vidéos/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_ligne', 'En ligne'), ('refuse', 'Refusé'), ('en_revision', 'En révision')], default='en_attente', max_length=15)),
                ('vues', models.PositiveIntegerField(default=0)),
                ('id_eke', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
